### ISSUE TITLE
Expansion for 'Swap Left Click On Wait' adding 'if under n seconds'

### ISSUE THREAD

**Issue by ctdgunner** [powerus117/RLAfkMarksCanafis#6]
To make this helpful even to non-afk add a sub option that will swap left click on wait only if under 'n' seconds.

If memory serves me right tick perfect Canafis is 43 or so seconds. So putting 8 seconds of delay from tick perfect (across 4 laps) allows me to get a mark every 4th lap (or at least roll for the 2/3 chance) If I could configure the swap left click option to allow me to get more XP during that wait time. [John Turner](https://www.youtube.com/@johnturner7313) explains it best in his youtube video: https://www.youtube.com/watch?v=ovqOB2LeHG4&list=PLOJsCHOKSDyLsUjhYjU-NSttmqZ5L3V5G&index=3

**Comment by powerus117** [comment]
Good suggestion! I will add it in the next update

**Comment by powerus117** [comment]
Implemented the suggestion. Did so on a full cooldown basis though as I didn't see any extra value in doing it per run. So it's going to block you from running within 32 seconds (configurable) before the cooldown rather than 8 seconds per run. Currently on PR with a bunch of other additions here https://github.com/runelite/plugin-hub/pull/6581
If you notice any issue after merge, let me know

**Comment by ctdgunner** [comment]
When you say run do you mean lap?

It sounds like you implemented it correctly. for Canafis it would be 8 seconds worth of delay needed for the entire mark of grace spawn. not 8 seconds per lap, no need to multiply that 8 by 4.

**Comment by powerus117** [comment]
Than all is good, it is also configurable so you can put in any amount of seconds you want, since it might be worth waiting x amount of seconds to get optimal mark spawns

**Comment by powerus117** [comment]
The suggestion should now be implemented, hope it functions as requested, if not, feel free to open another issue. Thanks for the feedback
